modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="create_cogs_invaders"
version="1.0.0"
displayName="Create Cogs Invaders"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="PC, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.create_cogs_invaders]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.create_cogs_invaders]]
    modId="use_compiled_mods"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.create_cogs_invaders]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.create_cogs_invaders]]
    modId="createnew"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration